export const INCREMENT = 'INCREMENT'
export const RESET = 'RESET'
export const FECTCH_NOTES = 'FECTCH_NOTES'
export const SELECT_INFO = 'SELECT_INFO'
export const REMOVE = 'REMOVE'
export const SET_USER = 'SET_USER'